blank_issues_enabled: true
contact_links:
  - about: Please discuss ideas and ask questions on the Purus discussion board.
    name: Ideas and Questions
    url: https://github.com/mlabs-haskell/purus/discussions
